#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 60000

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MOVE_DELTA 4
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 64
